#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
from dataclasses import dataclass
import time
import tempfile
import csv
import shutil
import pwd

# I found "root" and "boot" were too similar and difficult to
# disnguish at a glance so I prefer to call the root pool "main"

DISK_BY_ID = "/dev/disk/by-id"
MNT = "/mnt"
STAGE2_SCRIPT = "setup-zfs-stage2.sh"

# Make sure these do not have leading / otherwise os.path.join will not work
CONFIG_FILES = [
  "etc/apt/sources.list",
  "etc/default/keyboard",
  "etc/default/locale",
  "etc/group",
  "etc/gshadow",
  "etc/hostid",
  "etc/hostname",
  "etc/locale.gen",
  "etc/network/interfaces",
  "etc/passwd",
  "etc/shadow",
  "etc/timezone",
]

def build_argparser():
  parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument("disk", nargs="+", help="devices to use for disks or missing")
  parser.add_argument("--efi-size", default="512M", help="size of EFI partition")
  parser.add_argument("--boot-size", default="1G", help="size of /boot partition")
  parser.add_argument("--boot-pool", default="boot", help="name of boot pool")
  parser.add_argument("--main-pool", default="main", help="name of main pool")
  parser.add_argument("--raid-level", default="raidz2", help="raid level of main pool")
  parser.add_argument("--prefer-wwn", action="store_true", help="prefer /dev/disk/by-id/wwn-*")
  parser.add_argument("--collection", help="collection name, defaults to hostname")

  group = parser.add_mutually_exclusive_group()
  group.add_argument("--bios", action="store_true",
                     help="configure for legacy BIOS booting instead of EFI")
  group.add_argument("--efi", action="store_true", help="configure for EFI")

  return parser

@dataclass
class Disk:
  path: str
  device: str
  partitions: list

@dataclass
class Partition:
  path: str
  pool: str

def disk_by_id(path, preferWWN=False):
  dev = os.path.realpath(path)

  partitions = os.listdir(DISK_BY_ID)
  match = []
  for part in partitions:
    dest = os.readlink(os.path.join(DISK_BY_ID, part))
    if not os.path.isabs(dest):
      dest = os.path.join(DISK_BY_ID, dest)
      dest = os.path.realpath(dest)
    if dev == dest:
      match.append(part)

  if match:
    for part in match:
      if (part.startswith("wwn-") and preferWWN) \
         or (not part.startswith("wwn-") and not preferWWN):
        break
    return os.path.join(DISK_BY_ID, part)

  return None

def run_command(command, ignore_errors=False):
  print(command)
  p = subprocess.run(command)
  if not ignore_errors and p.returncode != 0:
    print("Failed", command)
    exit(1)
  return

def setup_partitions(disk, config_bios, efi_size, boot_size):
  run_command(["sgdisk", "--zap-all", disk])

  partitions = []
  pnum = 1
  if config_bios:
    run_command(["sgdisk", "-a1", f"-n{pnum}:24K:+1000K", f"-t{pnum}:EF02", disk])
    partitions.append(Partition(f"{disk}-part{pnum}", "efibios"))
  else:
    run_command(["sgdisk", f"-n{pnum}:1M:+{efi_size}", f"-t{pnum}:EF00", disk])
    partitions.append(Partition(f"{disk}-part{pnum}", "efibios"))
  pnum += 1

  run_command(["sgdisk", f"-n{pnum}:0:+{boot_size}", f"-t{pnum}:BF01", disk])
  partitions.append(Partition(f"{disk}-part{pnum}", "boot"))
  pnum += 1
  run_command(["sgdisk", f"-n{pnum}:0:0", f"-t{pnum}:BF00", disk])
  partitions.append(Partition(f"{disk}-part{pnum}", "main"))
  pnum += 1

  return partitions

def create_pool(pool_name, mount_point, partitions, mirror_type):
  cmd = ["zpool", "create", "-f",
         "-o", "ashift=12",
         "-o", "autotrim=on"]
  if pool_name == "boot":
    cmd.extend(["-o", "compatibility=grub2",
                "-o", "cachefile=/etc/zfs/zpool.cache",
                "-O", "devices=off"])
  else:
    cmd.extend(["-O", "dnodesize=auto"])

  cmd.extend(["-O", "acltype=posixacl",
              "-O", "xattr=sa",
              "-O", "compression=lz4",
              "-O", "normalization=formD",
              "-O", "relatime=on",
              "-O", "canmount=off",
              "-O", f"mountpoint={mount_point}",
              "-R", MNT,
              pool_name, mirror_type])
  cmd.extend([x.path for x in partitions])

  run_command(cmd)

  return

def get_partitions(pool_name, partitions):
  match = []
  missing = 0
  for group in partitions:
    if group is None:
      missing += 1
    else:
      for part in group:
        if part.pool == pool_name:
          match.append(part)

  if missing:
    sizes = []
    for part in match:
      cmd = ["blockdev", "--getsize64", part.path]
      output = subprocess.check_output(cmd)
      sizes.append(int(output.decode("utf-8")))
      sparse_size = min(sizes)

    for idx in range(missing):
      fake = tempfile.NamedTemporaryFile(dir="/tmp", delete=False)
      fake.truncate(sparse_size)
      match.append(Partition(fake.name, pool_name))

  return match

def offline_missing(partitions):
  for part in partitions:
    if part.path.startswith("/tmp/"):
      run_command(["zpool", "offline", part.pool, part.path])
      os.unlink(part.path)
  return

def create_dataset(dataset_name):
  run_command(["zfs", "create", "-o", "canmount=off", "-o", "mountpoint=none", dataset_name])
  return

def main():
  args = build_argparser().parse_args()
  boot_pool = args.boot_pool
  main_pool = args.main_pool

  config_bios = not args.efi and (args.bios or not os.path.exists("/sys/firmware/efi"))

  with open("/etc/os-release") as f:
    reader = csv.reader(f, delimiter="=")
    os_release = dict(reader)

  disks = []
  for path in args.disk:
    if path == "missing":
      disks.append(Disk(path, None, None))
      continue

    real = os.path.realpath(path)
    if re.search(r"\d+$", real):
      print("Need disk, not partition:", path)
      exit(1)

    disk = disk_by_id(path, args.prefer_wwn)
    if not disk:
      print("No such disk:", path)
      exit(1)
    disks.append(Disk(disk, os.path.realpath(disk), None))

  disks.sort(key=lambda x: x.device if x.device else "")

  for idx in range(len(disks)):
    if disks[idx].device:
      first = idx
      break

  run_command(["umount", "-R", MNT], ignore_errors=True)
  run_command(["zpool", "destroy", boot_pool], ignore_errors=True)
  run_command(["zpool", "destroy", main_pool], ignore_errors=True)

  partitions = []
  for disk in disks:
    if disk.device is not None:
      parts = setup_partitions(disk.path, config_bios, args.efi_size, args.boot_size)
      partitions.append(parts)
    else:
      partitions.append(None)

  # FIXME - must sleep and wait for partitions to be seen by kernel?
  time.sleep(1)

  boot_partitions = get_partitions("boot", partitions)
  create_pool(boot_pool, "/boot", boot_partitions, "mirror")
  offline_missing(boot_partitions)

  main_partitions = get_partitions("main", partitions)
  create_pool(main_pool, "/", main_partitions, args.raid_level)
  offline_missing(main_partitions)

  boot_dset = f"{boot_pool}/{boot_pool.upper()}"
  create_dataset(boot_dset)
  main_dset = f"{main_pool}/{main_pool.upper()}"
  create_dataset(main_dset)

  collection = args.collection
  if not collection:
    collection = os.uname().nodename

  # create filesystems

  run_command(["zfs", "create", "-o", "canmount=noauto", "-o", "mountpoint=/",
               f"{main_dset}/{collection}"])
  run_command(["zpool", "set", f"bootfs={main_dset}/{collection}", main_pool])
  run_command(["zfs", "mount", f"{main_dset}/{collection}"])

  run_command(["zfs", "create", "-o", "mountpoint=/boot", f"{boot_dset}/{collection}"])

  run_command(["zfs", "create", f"{main_pool}/home"])
  run_command(["zfs", "create", "-o", "mountpoint=/root", f"{main_pool}/home/root"])
  os.chmod(os.path.join(MNT, "root"), 0o700)

  run_command(["zfs", "create", "-o", "canmount=off", f"{main_pool}/var"])
  run_command(["zfs", "create", "-o", "canmount=off", f"{main_pool}/var/lib"])
  run_command(["zfs", "create", f"{main_pool}/var/log"])
  run_command(["zfs", "create", f"{main_pool}/var/spool"])

  run_command(["zfs", "create", "-o", "com.sun:auto-snapshot=false",
               f"{main_pool}/var/lib/docker"])

  print("#####################")
  print("Doing base OS install")
  print("#####################")
  print()

  run_command(["debootstrap", os_release['VERSION_CODENAME'], MNT])
  zfs_config_dir = os.path.join(MNT, "etc/zfs")
  if not os.path.exists(zfs_config_dir):
    os.mkdir(zfs_config_dir)
  shutil.copy("/etc/zfs/zpool.cache", zfs_config_dir)

  for path in CONFIG_FILES:
    print("copying", path)
    shutil.copyfile(os.path.join("/", path), os.path.join(MNT, path))

  users = pwd.getpwall()
  for user in users:
    home = user.pw_dir
    dest = os.path.join(MNT, home[1:])
    if os.path.exists(home) and not os.path.exists(dest):
      print("Copying home directory for", user.pw_name)
      run_command(["rsync", "--archive", home, os.path.join(os.path.dirname(dest), ".")])

  for path in ["dev", "proc", "sys"]:
    run_command(["mount", "--make-private", "--rbind",
                 os.path.join("/", path), os.path.join(MNT, path)])

  shutil.copy(STAGE2_SCRIPT, os.path.join(MNT, "root"))

  disk_order = " ".join([x.path for x in disks if x.device])
  efibios = "bios" if config_bios else "efi"
  run_command(["chroot", MNT, "/usr/bin/env",
               "TERM=vt100",
               f"DISK_ORDER={disk_order}",
               f"FIRST={disks[first].path}",
               f"DSET_MAIN={main_dset}",
               f"POOL_BOOT={boot_pool}",
               f"POOL_MAIN={main_pool}",
               f"BOOT_TYPE={efibios}",
               os.path.join("/root", STAGE2_SCRIPT)])

  return

if __name__ == '__main__':
  exit(main() or 0)
